"""follow.html upgrade

Revision ID: 2b53f73bf22b
Revises: a4f11f3b0754
Create Date: 2018-01-25 22:59:45.315463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b53f73bf22b'
down_revision = 'a4f11f3b0754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.drop_column('users', 'introduction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('introduction', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
